import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';

Widget graphImage() {
  return AspectRatio(
    aspectRatio: 2,
    child: LineChart(
      LineChartData(
        gridData: const FlGridData(
          show: false,
        ),
        borderData: FlBorderData(
          border: const Border(
            top: BorderSide(
              width: 0,
            ),
            right: BorderSide(
              width: 0,
            ),
            bottom: BorderSide(
              width: 2,
            ),
            left: BorderSide(
              width: 2,
            ),
          ),
        ),
        lineTouchData: LineTouchData(
          touchTooltipData: LineTouchTooltipData(
            tooltipBgColor: Colors.transparent,
            getTooltipItems: (touchedSpots) {
              return touchedSpots.map(
                (LineBarSpot touchedSpot) {
                  return LineTooltipItem(
                      '${touchedSpot.y}',
                      const TextStyle(
                        color: Colors.black,
                        fontWeight: FontWeight.w800,
                      ));
                },
              ).toList();
            },
          ),
        ),
        lineBarsData: [
          LineChartBarData(
            preventCurveOverShooting: true,
            dotData: const FlDotData(
              show: false,
            ),
            curveSmoothness: 0.5,
            barWidth: 2,
            spots: const [
              FlSpot(1, 120),
              FlSpot(2, 136),
              FlSpot(3, 130),
              FlSpot(4, 122),
              FlSpot(5, 140),
              FlSpot(6, 160),
              FlSpot(7, 170),
              FlSpot(8, 180),
              FlSpot(9, 200),
              FlSpot(10, 240),
              FlSpot(11, 270),
              FlSpot(12, 340),
              FlSpot(13, 480),
              FlSpot(14, 660),
              FlSpot(15, 915),
              FlSpot(16, 780),
              FlSpot(17, 320),
              FlSpot(18, 260),
              FlSpot(19, 340),
              FlSpot(20, 455),
              FlSpot(21, 500),
              FlSpot(22, 498),
              FlSpot(23, 530),
              FlSpot(24, 505),
              FlSpot(25, 499),
              FlSpot(26, 520),
              FlSpot(27, 350),
              FlSpot(28, 320),
              FlSpot(29, 220),
              FlSpot(30, 244),
            ],
            isCurved: true,
            color: Colors.blue,
          ),
          LineChartBarData(
            preventCurveOverShooting: true,
            dotData: const FlDotData(
              show: false,
            ),
            curveSmoothness: 0.5,
            barWidth: 2,
            spots: const [
              FlSpot(1, 98),
              FlSpot(2, 136),
              FlSpot(3, 140),
              FlSpot(4, 145),
              FlSpot(5, 150),
              FlSpot(6, 155),
              FlSpot(7, 150),
              FlSpot(8, 145),
              FlSpot(9, 148),
              FlSpot(10, 140),
              FlSpot(11, 120),
              FlSpot(12, 102),
              FlSpot(13, 100),
              FlSpot(14, 98),
              FlSpot(15, 110),
              FlSpot(16, 260),
              FlSpot(17, 190),
              FlSpot(18, 140),
              FlSpot(19, 120),
              FlSpot(20, 100),
              FlSpot(21, 90),
              FlSpot(22, 80),
              FlSpot(23, 70),
              FlSpot(24, 60),
              FlSpot(25, 50),
              FlSpot(26, 50),
              FlSpot(27, 60),
              FlSpot(28, 63),
              FlSpot(29, 90),
              FlSpot(30, 80),
            ],
            isCurved: true,
            color: Colors.deepPurple,
          ),
          LineChartBarData(
            preventCurveOverShooting: true,
            dotData: const FlDotData(
              show: false,
            ),
            curveSmoothness: 0.5,
            barWidth: 2,
            spots: const [
              FlSpot(1, 60),
              FlSpot(2, 80),
              FlSpot(3, 90),
              FlSpot(4, 80),
              FlSpot(5, 95),
              FlSpot(6, 100),
              FlSpot(7, 100),
              FlSpot(8, 115),
              FlSpot(9, 120),
              FlSpot(10, 110),
              FlSpot(11, 100),
              FlSpot(12, 105),
              FlSpot(13, 120),
              FlSpot(14, 160),
              FlSpot(15, 280),
              FlSpot(16, 950),
              FlSpot(17, 320),
              FlSpot(18, 170),
              FlSpot(19, 150),
              FlSpot(20, 140),
              FlSpot(21, 110),
              FlSpot(22, 120),
              FlSpot(23, 90),
              FlSpot(24, 80),
              FlSpot(25, 70),
              FlSpot(26, 60),
              FlSpot(27, 65),
              FlSpot(28, 80),
              FlSpot(29, 70),
              FlSpot(30, 70),
            ],
            isCurved: true,
            color: Colors.green,
          ),
          LineChartBarData(
            preventCurveOverShooting: true,
            dotData: const FlDotData(
              show: false,
            ),
            curveSmoothness: 0.5,
            barWidth: 2,
            spots: const [
              FlSpot(1, 40),
              FlSpot(2, 30),
              FlSpot(3, 20),
              FlSpot(4, 15),
              FlSpot(5, 10),
              FlSpot(6, 20),
              FlSpot(7, 15),
              FlSpot(8, 10),
              FlSpot(9, 15),
              FlSpot(10, 10),
              FlSpot(11, 10),
              FlSpot(12, 10),
              FlSpot(13, 10),
              FlSpot(14, 10),
              FlSpot(15, 20),
              FlSpot(16, 60),
              FlSpot(17, 110),
              FlSpot(18, 265),
              FlSpot(19, 460),
              FlSpot(20, 670),
              FlSpot(21, 800),
              FlSpot(22, 810),
              FlSpot(23, 900),
              FlSpot(24, 880),
              FlSpot(25, 750),
              FlSpot(26, 760),
              FlSpot(27, 400),
              FlSpot(28, 380),
              FlSpot(29, 230),
              FlSpot(30, 215),
            ],
            isCurved: true,
            color: Colors.red,
          ),
        ],
      ),
    ),
  );
}
